using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum AZIONICOMBATTIMENTO
{
    FERMO,
    ATTACCA,
    USAPOZIONE,
    FUGGI,
}

public enum AZIONIMOVIMENTO
{
    
    STAI,
    AVANTI,
    INDIETRO

}

public enum AZIONIINVENTARIO
{
    NULLA,
    PRENDOPOZIONECURA,
    PRENDOPOZIONEANTIDOTO,
    PRENDOPOZIONEANTIBRUCIATURA,
    PRENDOPOZIONEANTIGELO,
    PRENDOPOZIOCONCENTRAZIONE
}